// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb)
      throw UnsupportedError('AniWings requires a native desktop build.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidPreview;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidPreview = FirebaseOptions(
    apiKey: 'AIzaSyDxmjBv9LUoy51kotDNXzJNz-N-JggBkA4',
    appId: '1:961563973576:android:e4ed11fab16242c91c92fd',
    messagingSenderId: '961563973576',
    projectId: 'aniwings-9beea',
    storageBucket: 'aniwings-9beea.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeryDLWsVld1-dWN5KqwJPo6CQlVXMgss',
    appId: '1:961563973576:web:838257dc384065131c92fd',
    messagingSenderId: '961563973576',
    projectId: 'aniwings-9beea',
    authDomain: 'aniwings-9beea.firebaseapp.com',
    storageBucket: 'aniwings-9beea.firebasestorage.app',
    measurementId: 'G-BMXTKB104T',
  );
}
